// Loads each sprite as its own PNG from /public/sprites/cut/. The cut PNGs are
// generated by `scripts/cut-sprites.mjs`. Each file is the exact bounding box
// of one sprite — no source rects, no neighbour bleed.

export type SpriteName =
  | "frog_idle"
  | "frog_hop"
  | "frog_squash"
  | "frog_drown_1"
  | "frog_drown_2"
  | "frog_drown_3"
  | "frog_in_home"
  | "car_yellow"
  | "car_white"
  | "car_purple"
  | "car_green"
  | "truck"
  | "turtle_a"
  | "turtle_b"
  | "turtle_c"
  | "turtle_dive"
  | "turtle_submerged"
  | "log_l"
  | "log_m"
  | "log_r"
  | "bonus_fly"
  | "croc_head"
  | "croc_body"
  | "snake_a"
  | "snake_b"
  | "snake_c"
  | "lady_frog";

// Reason: GitHub Pages (and Vite base) need paths under import.meta.env.BASE_URL.
const asset = (path: string): string =>
  `${import.meta.env.BASE_URL}${path.replace(/^\//, "")}`;

const SPRITE_PATHS: Record<SpriteName, string> = {
  frog_idle: asset("sprites/cut/frog_idle.png"),
  frog_hop: asset("sprites/cut/frog_hop.png"),
  frog_squash: asset("sprites/cut/frog_squash.png"),
  frog_drown_1: asset("sprites/cut/frog_drown_1.png"),
  frog_drown_2: asset("sprites/cut/frog_drown_2.png"),
  frog_drown_3: asset("sprites/cut/frog_drown_3.png"),
  frog_in_home: asset("sprites/cut/frog_in_home.png"),
  car_yellow: asset("sprites/cut/car_yellow.png"),
  car_white: asset("sprites/cut/car_white.png"),
  car_purple: asset("sprites/cut/car_purple.png"),
  car_green: asset("sprites/cut/car_green.png"),
  truck: asset("sprites/cut/truck.png"),
  turtle_a: asset("sprites/cut/turtle_a.png"),
  turtle_b: asset("sprites/cut/turtle_b.png"),
  turtle_c: asset("sprites/cut/turtle_c.png"),
  turtle_dive: asset("sprites/cut/turtle_dive.png"),
  turtle_submerged: asset("sprites/cut/turtle_submerged.png"),
  log_l: asset("sprites/cut/log_l.png"),
  log_m: asset("sprites/cut/log_m.png"),
  log_r: asset("sprites/cut/log_r.png"),
  bonus_fly: asset("sprites/cut/bonus_fly.png"),
  croc_head: asset("sprites/cut/croc_head.png"),
  croc_body: asset("sprites/cut/croc_body.png"),
  snake_a: asset("sprites/cut/snake_a.png"),
  snake_b: asset("sprites/cut/snake_b.png"),
  snake_c: asset("sprites/cut/snake_c.png"),
  lady_frog: asset("sprites/cut/lady_frog.png"),
};

export class SpriteSheet {
  private images = new Map<SpriteName, HTMLImageElement>();
  private ready = false;
  private waiters: Array<() => void> = [];

  constructor() {
    const names = Object.keys(SPRITE_PATHS) as SpriteName[];
    let remaining = names.length;
    for (const name of names) {
      const img = new Image();
      img.onload = () => {
        this.images.set(name, img);
        remaining--;
        if (remaining === 0) {
          this.ready = true;
          this.waiters.splice(0).forEach((w) => w());
        }
      };
      img.onerror = () => {
        console.error(`Failed to load sprite: ${name} from ${SPRITE_PATHS[name]}`);
        remaining--;
        if (remaining === 0) {
          this.ready = true;
          this.waiters.splice(0).forEach((w) => w());
        }
      };
      img.src = SPRITE_PATHS[name];
    }
  }

  whenReady(): Promise<void> {
    if (this.ready) return Promise.resolve();
    return new Promise((resolve) => this.waiters.push(resolve));
  }

  isReady(): boolean {
    return this.ready;
  }

  size(name: SpriteName): { w: number; h: number } | null {
    const img = this.images.get(name);
    if (!img) return null;
    return { w: img.naturalWidth, h: img.naturalHeight };
  }

  // Draws sprite centered at (cx, cy), at the given pixel size. Optional
  // rotation around the center.
  drawCentered(
    ctx: CanvasRenderingContext2D,
    name: SpriteName,
    cx: number,
    cy: number,
    size: number,
    rotation = 0
  ): void {
    const img = this.images.get(name);
    if (!img) return;
    ctx.save();
    ctx.translate(cx, cy);
    if (rotation !== 0) ctx.rotate(rotation);
    ctx.drawImage(img, -size / 2, -size / 2, size, size);
    ctx.restore();
  }

  // Stretches sprite to fit a destination rect, optional horizontal flip.
  drawStretched(
    ctx: CanvasRenderingContext2D,
    name: SpriteName,
    dx: number,
    dy: number,
    dw: number,
    dh: number,
    flipX = false
  ): void {
    const img = this.images.get(name);
    if (!img) return;
    if (flipX) {
      ctx.save();
      ctx.translate(dx + dw, dy);
      ctx.scale(-1, 1);
      ctx.drawImage(img, 0, 0, dw, dh);
      ctx.restore();
    } else {
      ctx.drawImage(img, dx, dy, dw, dh);
    }
  }

  // Draws a source crop of the sprite stretched into a dest rect.
  drawCropped(
    ctx: CanvasRenderingContext2D,
    name: SpriteName,
    sx: number,
    sy: number,
    sw: number,
    sh: number,
    dx: number,
    dy: number,
    dw: number,
    dh: number
  ): void {
    const img = this.images.get(name);
    if (!img) return;
    ctx.drawImage(img, sx, sy, sw, sh, dx, dy, dw, dh);
  }

  // 3-slice: keeps native edges, tiles the middle to fill width. Used for logs.
  drawThreeSlice(
    ctx: CanvasRenderingContext2D,
    name: SpriteName,
    dx: number,
    dy: number,
    dw: number,
    dh: number,
    capW: number,
    flipX = false
  ): void {
    const img = this.images.get(name);
    if (!img) return;
    const sw = img.naturalWidth;
    const sh = img.naturalHeight;
    const tileSrcStart = capW;
    const tileSrcW = sw - capW * 2;
    const destCapW = capW * 2;

    const draw = (): void => {
      ctx.drawImage(img, 0, 0, capW, sh, 0, 0, destCapW, dh);
      ctx.drawImage(img, sw - capW, 0, capW, sh, dw - destCapW, 0, destCapW, dh);
      const middleStart = destCapW;
      const middleEnd = dw - destCapW;
      const tileDestW = tileSrcW * 2;
      let mx = middleStart;
      while (mx < middleEnd) {
        const remaining = middleEnd - mx;
        const drawW = Math.min(tileDestW, remaining);
        const drawSrcW = (drawW / tileDestW) * tileSrcW;
        ctx.drawImage(img, tileSrcStart, 0, drawSrcW, sh, mx, 0, drawW, dh);
        mx += drawW;
      }
    };

    ctx.save();
    if (flipX) {
      ctx.translate(dx + dw, dy);
      ctx.scale(-1, 1);
    } else {
      ctx.translate(dx, dy);
    }
    draw();
    ctx.restore();
  }

  drawRotatedSized(
    ctx: CanvasRenderingContext2D,
    name: SpriteName,
    cx: number,
    cy: number,
    visualW: number,
    visualH: number,
    rotation: number
  ): void {
    const img = this.images.get(name);
    if (!img) return;
    ctx.save();
    ctx.translate(cx, cy);
    ctx.rotate(rotation);
    const isQuarterTurn = Math.abs(Math.sin(rotation)) > 0.5;
    const dw = isQuarterTurn ? visualH : visualW;
    const dh = isQuarterTurn ? visualW : visualH;
    ctx.drawImage(img, -dw / 2, -dh / 2, dw, dh);
    ctx.restore();
  }
}
